id: I413EC0B0
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:10:03.329712+00:00
last_modified: 2022-12-14 18:10:03.329717+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-035
  eft-text-version: 1.1.5 2020
  title: Toh_335-The_Sutra_on_the_Ringing_Staff-v2
bases:
  BF12:
    source_metadata: null
    order: 1
    base_file: BF12.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
